import { Inter } from "@next/font/google";
import Head from "next/head";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Screenz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
}

export const getServersideProps = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
};
